[build]
  command = "npm install --production=false && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.19.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Next.js App Router redirects
[[redirects]]
  from = "/dashboard/*"
  to = "/dashboard"
  status = 200

[[redirects]]
  from = "/users/*"
  to = "/users"
  status = 200

[[redirects]]
  from = "/deviations/*"
  to = "/deviations"
  status = 200

[[redirects]]
  from = "/documents/*"
  to = "/documents"
  status = 200

[[redirects]]
  from = "/shifts/*"
  to = "/shifts"
  status = 200

[[redirects]]
  from = "/reports/*"
  to = "/reports"
  status = 200

[[redirects]]
  from = "/settings/*"
  to = "/settings"
  status = 200

[[redirects]]
  from = "/help/*"
  to = "/help"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://www.gstatic.com https://www.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://firestore.googleapis.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com;"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development" 